spring:
  application:
    name: toolsyde-generator

  datasource:
    url: jdbc:postgresql://localhost:5432/pgdb
    driver-class-name: org.postgresql.Driver
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect